### ISSUE TITLE
wireguard will fail after reinstallation after uninstallation  in Debian12

### ISSUE THREAD

**Issue by limitwhy** [hwdsl2/wireguard-install#28] opened 2023-12-13 23:32 UTC
Do you want to continue? [Y/n] y

Installing WireGuard, please wait...
+ apt-get -yqq update
+ apt-get -yqq install wireguard qrencode
Error: 'apt-get install' failed.

**Comment by hwdsl2** [comment] 2023-12-14 14:16
@limitwhy Hello! This error is usually caused by a temporary issue with the apt-get repositories, and can be resolved by trying the install again.

To see detailed error messages, edit the script and change "-yqq" to "-y" in "apt-get -yqq install wireguard qrencode", then run the script to install.

**Closed** 2023-12-14 14:16 UTC

**Comment by phant** [comment] 2024-05-18 12:01
this is not fixed, output without quiet
```
Installing WireGuard, please wait...
+ apt-get -y update
Hit:1 http://deb.debian.org/debian bookworm InRelease
Hit:2 http://deb.debian.org/debian-security bookworm-security InRelease
Hit:3 http://deb.debian.org/debian bookworm-updates InRelease
Reading package lists... Done
+ apt-get -y install wireguard qrencode
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  qrencode wireguard
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/50.8 kB of archives.
After this operation, 98.3 kB of additional disk space will be used.
Selecting previously unselected package qrencode.
(Reading database ... 44237 files and directories currently installed.)
Preparing to unpack .../qrencode_4.1.1-1_amd64.deb ...
Unpacking qrencode (4.1.1-1) ...
Selecting previously unselected package wireguard.
Preparing to unpack .../wireguard_1.0.20210914-1_all.deb ...
Unpacking wireguard (1.0.20210914-1) ...
Setting up qrencode (4.1.1-1) ...
Setting up wireguard (1.0.20210914-1) ...
Processing triggers for man-db (2.11.2-2) ...
Error: 'apt-get install' failed.
```

**Comment by hwdsl2** [comment] 2024-05-18 15:40
@phant Hello! I could not reproduce this issue on a new Debian 12 server. This issue is usually caused by temporary issues with your server's package repositories. Try running the script again, or use a different server.

**Comment by phant** [comment] 2024-05-19 09:32
> @phant Hello! I could not reproduce this issue on a new Debian 12 server. 
manual execution of `apt-get -y install wireguard qrencode` show no errors.

Maybe me and topic starter run your l2tp+ipsec script and afrer that wireguard script.
try to install setup-ipsec-vpn
after that wireguard-install
after - remove wireguard-install
and install again
